Number=4321
Reverse=0
Reminder=0
print(Number)
Reminder=Number%10
print(Reminder)
Reverse=Reverse*10+Reminder
print(Reverse)
Number=Number//10
print(Number)
Number=432
Reverse=1
Reminder=Number%10
print(Reminder)
Reverse=Reverse*10+Reminder
print(Reverse)
Number=Number//10
print(Number)
Number=43
Reverse=12
Reminder=Number%10
print(Reminder)
Reverse=Reverse*10+Reminder
print(Reverse)
Number=Number//10
print(Number)
Number=4
Reverse=123
Reminder=Number%10
print(Reminder)
Reverse=Reverse*10+Reminder
print(Reverse)
